version: '3'
services:
  db:
    image: mariadb:10.6.5
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
  app:
    image:  demo-market-project
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/main/resources/application.properties:/usr/app/application.properties
