version: '3.1'
services:
  db:
    image: mysql:5.7.22
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - /usr/local/var/mysql:/var/lib/mysql

  demo-market-project-java:
    image:  demo-market-project
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./src/main/resources/application-prod.properties:/usr/app/application-prod.properties
